server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy clientes
    location /api/clientes/ {
        proxy_pass http://bp-customer-service:9080/;
    }

    # Proxy cuentas
    location /api/cuentas/ {
        proxy_pass http://bp-banking-service:9081/;
    }

    # Proxy movimientos
    location /api/movimientos/ {
        proxy_pass http://bp-banking-service:9081/;
    }
}